# Generated by Django 4.0.6 on 2022-07-18 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=32)),
                ('user_ip', models.CharField(max_length=40)),
                ('content', models.CharField(max_length=256)),
                ('created_at', models.DateTimeField()),
            ],
        ),
    ]
